export const BOARD_ACTIONS = {
  CHANGE_TOOL: "CHANGE_TOOL",
  START_DRAWING: "START_DRAWING",
  FINISH_DRAWING: "FINISH_DRAWING",
  ADD_NEW_LINE_ELEMENT: "ADD_NEW_LINE_ELEMENT",
  UPDATE_LINE_ELEMENT: "UPDATE_LINE_ELEMENT",
  ADD_PENCIL_POINT: "ADD_PENCIL_POINT",
  SET_TOOL_ACTION: "SET_TOOL_ACTION",
  SET_SELECTED_ELEMENT: "SET_SELECTED_ELEMENT",
  FINISH_SKETCHING: "FINISH_SKETCHING",
};
