export const BOARD_ACTIONS = {
  CHANGE_TOOL: "CHANGE_TOOL",
  START_DRAWING: "START_DRAWING",
  FINISH_DRAWING: "FINISH_DRAWING",
  ADD_NEW_LINE_ELEMENT: "ADD_NEW_LINE_ELEMENT",
  UPDATE_LAST_LINE_ELEMENT: "UPDATE_LAST_LINE_ELEMENT",
};
