export const TOOL_ITEMS = {
  PENCIL: "PENCIL",
  LINE: "LINE",
  RECTANGLE: "RECTANGLE",
  CIRCLE: "CIRCLE",
};

export const TOOL_ACTION_TYPES = {
  NONE: "NONE",
  DRAWING: "DRAWING",
  SKETCHING: "SKETCHING",
};

export const BOARD_ACTIONS = {
  CHANGE_TOOL: "CHANGE_TOOL",
  SKETCH_DOWN: "SKETCH_DOWN",
  DRAW_DOWN: "DRAW_DOWN",
  SKETCH_MOVE: "SKETCH_MOVE",
  DRAW_MOVE: "DRAW_MOVE",
  DRAW_UP: "DRAW_UP",
  SKETCH_UP: "SKETCH_UP",
};
