export const TOOL_ITEMS = {
  PENCIL: "PENCIL",
  LINE: "LINE",
  RECTANGLE: "RECTANGLE",
  CIRCLE: "CIRCLE",
  ERASER: "ERASER",
  ARROW: "ARROW",
};

export const TOOL_ACTION_TYPES = {
  NONE: "NONE",
  DRAWING: "DRAWING",
  SKETCHING: "SKETCHING",
  ERASING: "ERASING",
};

export const BOARD_ACTIONS = {
  CHANGE_TOOL: "CHANGE_TOOL",
  SKETCH_DOWN: "SKETCH_DOWN",
  DRAW_DOWN: "DRAW_DOWN",
  SKETCH_MOVE: "SKETCH_MOVE",
  DRAW_MOVE: "DRAW_MOVE",
  DRAW_UP: "DRAW_UP",
  SKETCH_UP: "SKETCH_UP",
  ERASE: "ERASE",
};

export const TOOLBOX_ACTIONS = {
  CHANGE_STROKE: "CHANGE_STROKE",
  CHANGE_FILL: "CHANGE_FILL",
  CHANGE_SIZE: "CHANGE_SIZE",
};

export const COLORS = {
  BLACK: "black",
  RED: "red",
  GREEN: "green",
  BLUE: "blue",
  ORANGE: "orange",
  YELLOW: "yellow",
  WHITE: "WHITE",
};

export const COLOR_CONFIG_TYPES = {
  STROKE: "STROKE",
  FILL: "FILL",
};

export const STROKE_TOOL_ITEMS = [
  TOOL_ITEMS.LINE,
  TOOL_ITEMS.PENCIL,
  TOOL_ITEMS.RECTANGLE,
  TOOL_ITEMS.CIRCLE,
  TOOL_ITEMS.ARROW,
];

export const ELEMENT_ERASE_THRESHOLDS = {
  LINE: 0.1,
  RECTANGLE: 2,
};

export const ARROW_LENGTH = 20;

export const FILL_TOOL_ITEMS = [TOOL_ITEMS.RECTANGLE, TOOL_ITEMS.CIRCLE];
